import = ["/home/sabby/.config/alacritty/themes/themes/catppuccin-macchiato.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[window]
decorations = "none"
opacity = 0.9
startup_mode = "Fullscreen"

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape="Block"

[font]
size = 12.0

[font.normal]
family = "GeistMono Nerd Font"
style = "Bold"

[selection]
save_to_clipboard = true
