import = ["/home/sabby/.config/alacritty/themes/themes/tokyo-night.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[window.dimensions]
columns = 80
lines = 30

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape="Block"

[font]
size = 12.0

[font.normal]
family = "GeistMono Nerd Font"
style = "Bold"

[selection]
save_to_clipboard = true
